### ISSUE TITLE
Can't put array

### ISSUE THREAD

**Issue by amorygalili** [robotpy/pynetworktables2js#12]
Currently I can't say `NetworkTables.putValue('/key', [1,2,3])` Adding arrays isn't that easy because nt wouldn't like `NetworkTables.putValue('/key', [])` because it needs a type and it can't get a type from an empty array. I think we should have separate methods 'putBooleanArray', 'putNumberArray', 'putStringArray', or require a third parameter 'type' for putValue when adding an array. It would look something like `NetworkTables.putValue('/key', [1,2,3], 'Integer')`

**Comment by auscompgeek** [comment]
I suspect this is no longer true this year.

**Comment by virtuald** [comment]
We should verify this before the 2018 season.

**Comment by auscompgeek** [comment]
I can confirm with pynetworktables and pynetworktables2js 2017 that `NetworkTables.putValue('/key', [1, 2, 3])` and `NetworkTables.putValue('/key2', ['a', 'b', 'c'])` work as expected.
