### ISSUE TITLE
Cannot Connect to Robot

### ISSUE THREAD

**Issue by TheWhiteBreadMan** [robotpy/pynetworktables2js#8]
We're trying to connect to the Roborio for the 2016 competition, and we are not connecting to the robot. I am running:
`.\tornado_server.py --robot roborio-3322.local`
And I am attempting to connect to the robot via:
`localhost:8888`
The web socket is connected, but the robot isn't connected to the computer.

**Comment by PeterJohnson** [comment]
The robot name is roborio-3322-frc.local this year (note the added "-frc").

**Comment by TheWhiteBreadMan** [comment]
Thank you!
