### ISSUE TITLE
Running JS from arbitrary JS

### ISSUE THREAD

**Issue by Arhowk** [robotpy/pynetworktables2js#9]
I don't have a ton of robot time to be chasing my tail around this so I just want to see if it is viable...

I'd like to implement the JS network tables in my Qt dashboard because I couldn't compile a DLL if my life was on the line. If I start the generic tornado server on my RIO, can I just drop the networktables.js (with appropriate hacking to fix the IP resolution and WebSocket usage) and it would work fine?

**Comment by virtuald** [comment]
Sounds like a pain, but I don't see any reason why it wouldn't work. I generally recommend running the tornado server on the driver station, instead of on the RIO.

**Comment by virtuald** [comment]
Did you get this to work?

**Comment by Arhowk** [comment]
Before i had to throw away all of the dashboard code, I was using a tcp
socket instead. I do not remember the reason to switch from the net tables
to the socket. I also don't believe I ever tested this.
